server:
  port: 8081

spring:
  application:
    name: patient-service

  datasource:
    url: ${PATIENT_DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
 
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:kafka:9092}
    consumer:
      group-id: patient-saga-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      auto-startup: false
      missing-topics-fatal: false    

info:
  app:
    name: patient-service
    description: Hospital Management Patient Service
    version: 0.0.1-SNAPSHOT

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}

  instance:
    hostname: patient-service
    prefer-ip-address: false
    status-page-url: http://patient-service:${server.port}/actuator/info
    health-check-url: http://patient-service:${server.port}/actuator/health

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [traceId=%X{traceId}, spanId=%X{spanId}] - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      probes:
        enabled: true

  info:
    env:
      enabled: true

  tracing:
    exporter:
      otlp:
        endpoint: ${OTEL_ENDPOINT}

  otlp:
    metrics:
      export:
        url: ${OTEL_METRICS_ENDPOINT}      