<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.hospital</groupId>
    <artifactId>hospital-management-system</artifactId>
    <version>1.0.0</version>

    <packaging>pom</packaging>

    <name>hospital-management-system</name>
    <description>Hospital Management System - Microservices</description>

    <modules>

        <!-- Shared library -->
        <module>common/hospital-common</module>

        <!-- Infrastructure -->
        <module>services/eureka-server</module>
        <module>services/api-gateway</module>

        <!-- Business services -->
        <module>services/patient-service</module>
        <module>services/doctor-service</module>
        <module>services/appointment-service</module>

    </modules>

</project>