spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: patient-service
              uri: lb://patient-service
              predicates:
                - Path=/api/patients/**

            - id: doctor-service
              uri: lb://doctor-service
              predicates:
                - Path=/api/doctors/**
                
            - id: appointment-service
              uri: lb://appointment-service
              predicates:
                - Path=/api/appointments/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - gateway
          

  endpoint:
    health:
      probes:
        enabled: true

  info:
    env:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    description: Hospital Management API Gateway
    version: 0.0.1-SNAPSHOT

logging:
  level:
    org.springframework.cloud.gateway: DEBUG