server:
  port: 8081

spring:
  application:
    name: patient-service

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      probes:
        enabled: true

  info:
    env:
      enabled: true

info:
  app:
    name: patient-service
    description: Hospital Management Patient Service
    version: 0.0.1-SNAPSHOT